BEGIN;
ALTER TABLE users ADD COLUMN IF NOT EXISTS username text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS coins integer NOT NULL DEFAULT 500 CHECK(coins>=0);
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile jsonb NOT NULL DEFAULT '{}';
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
CREATE UNIQUE INDEX IF NOT EXISTS users_username_unique ON users(username);
ALTER TABLE mochis ADD COLUMN IF NOT EXISTS profile jsonb NOT NULL DEFAULT '{}';
ALTER TABLE mochis ADD COLUMN IF NOT EXISTS last_pet_tick bigint NOT NULL DEFAULT 0;
ALTER TABLE mochi_brains ADD COLUMN IF NOT EXISTS checkpoint_key text;
ALTER TABLE mochi_brains ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 0;
ALTER TABLE mochi_brains ADD COLUMN IF NOT EXISTS lease_token text;
ALTER TABLE mochi_brains ADD COLUMN IF NOT EXISTS lease_until timestamptz;
ALTER TABLE mochi_brains ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
CREATE TABLE IF NOT EXISTS game_sessions(id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS player_inventory(user_id text REFERENCES users(id),item_id text REFERENCES items(id),location text NOT NULL DEFAULT 'bag' CHECK(location IN('bag','storage')),quantity integer NOT NULL CHECK(quantity>=0),PRIMARY KEY(user_id,item_id,location));
CREATE TABLE IF NOT EXISTS collection_entries(user_id text REFERENCES users(id),item_id text REFERENCES items(id),discovered_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(user_id,item_id));
CREATE TABLE IF NOT EXISTS shops(id text PRIMARY KEY,slug text UNIQUE NOT NULL,data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS shop_stock(shop_id text REFERENCES shops(id),item_id text REFERENCES items(id),quantity integer NOT NULL CHECK(quantity>=0),price integer NOT NULL CHECK(price>=0),cycle bigint NOT NULL,stocked_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(shop_id,item_id));
CREATE TABLE IF NOT EXISTS player_shops(user_id text PRIMARY KEY REFERENCES users(id),title text NOT NULL,description text NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS player_shop_listings(id text PRIMARY KEY,seller_id text NOT NULL REFERENCES users(id),item_id text NOT NULL REFERENCES items(id),quantity integer NOT NULL CHECK(quantity>0),price integer NOT NULL CHECK(price>0),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS currency_transactions(id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),amount integer NOT NULL,type text NOT NULL,related_user_id text REFERENCES users(id),related_item_id text REFERENCES items(id),created_at timestamptz NOT NULL DEFAULT now(),metadata jsonb NOT NULL DEFAULT '{}');
CREATE INDEX IF NOT EXISTS currency_transactions_user ON currency_transactions(user_id,created_at DESC);
CREATE TABLE IF NOT EXISTS daily_claims(user_id text REFERENCES users(id),activity text,day date,reward integer NOT NULL CHECK(reward>=0),data jsonb NOT NULL DEFAULT '{}',PRIMARY KEY(user_id,activity,day));
CREATE TABLE IF NOT EXISTS user_events(id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),type text NOT NULL,payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),read_at timestamptz);
CREATE TABLE IF NOT EXISTS mochi_preferences(mochi_id text REFERENCES mochis(id),kind text,item_id text,score integer NOT NULL DEFAULT 0,PRIMARY KEY(mochi_id,kind,item_id));
CREATE TABLE IF NOT EXISTS mochi_relationships(mochi_a_id text REFERENCES mochis(id),mochi_b_id text REFERENCES mochis(id),familiarity integer DEFAULT 0,affection integer DEFAULT 0,rivalry integer DEFAULT 0,trust integer DEFAULT 0,interactions integer DEFAULT 0,last_interaction_at timestamptz,PRIMARY KEY(mochi_a_id,mochi_b_id),CHECK(mochi_a_id<>mochi_b_id));
CREATE TABLE IF NOT EXISTS achievement_definitions(id text PRIMARY KEY,data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS user_achievements(user_id text REFERENCES users(id),achievement_id text REFERENCES achievement_definitions(id),earned_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(user_id,achievement_id));
CREATE TABLE IF NOT EXISTS trophies(id text PRIMARY KEY,data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS user_trophies(user_id text REFERENCES users(id),trophy_id text REFERENCES trophies(id),earned_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(user_id,trophy_id));
CREATE TABLE IF NOT EXISTS mochi_trophies(mochi_id text REFERENCES mochis(id),trophy_id text REFERENCES trophies(id),earned_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(mochi_id,trophy_id));
CREATE TABLE IF NOT EXISTS friend_requests(id text PRIMARY KEY,sender_id text NOT NULL REFERENCES users(id),recipient_id text NOT NULL REFERENCES users(id),status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','accepted','declined')),created_at timestamptz NOT NULL DEFAULT now(),CHECK(sender_id<>recipient_id));
CREATE UNIQUE INDEX IF NOT EXISTS pending_friend_request ON friend_requests(least(sender_id,recipient_id),greatest(sender_id,recipient_id)) WHERE status='pending';
CREATE TABLE IF NOT EXISTS friendships(user_a_id text REFERENCES users(id),user_b_id text REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(user_a_id,user_b_id),CHECK(user_a_id<user_b_id));
CREATE TABLE IF NOT EXISTS arcade_rounds(id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),started_at timestamptz NOT NULL DEFAULT now(),ends_at timestamptz NOT NULL,seed integer NOT NULL,hits jsonb NOT NULL DEFAULT '[]',claimed boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS arcade_scores(id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),round_id text UNIQUE REFERENCES arcade_rounds(id),score integer NOT NULL CHECK(score>=0),reward integer NOT NULL CHECK(reward>=0),day date NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS competitions(id text PRIMARY KEY,name text NOT NULL,starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL,status text NOT NULL DEFAULT 'open',config jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS competition_entries(competition_id text REFERENCES competitions(id),mochi_id text REFERENCES mochis(id),user_id text NOT NULL REFERENCES users(id),portfolio jsonb NOT NULL,trades jsonb NOT NULL DEFAULT '[]',pending jsonb,last_tick_at timestamptz,rank integer,reward integer NOT NULL DEFAULT 0,settled_at timestamptz,PRIMARY KEY(competition_id,mochi_id));
CREATE TABLE IF NOT EXISTS trading_post_offers(id text PRIMARY KEY,user_id text REFERENCES users(id),items jsonb NOT NULL,requested jsonb NOT NULL,status text NOT NULL DEFAULT 'draft');
CREATE TABLE IF NOT EXISTS auctions(id text PRIMARY KEY,seller_id text REFERENCES users(id),item_id text REFERENCES items(id),quantity integer NOT NULL CHECK(quantity>0),minimum_bid integer NOT NULL CHECK(minimum_bid>=0),ends_at timestamptz,status text NOT NULL DEFAULT 'draft');
CREATE TABLE IF NOT EXISTS guilds(id text PRIMARY KEY,name text NOT NULL,description text NOT NULL DEFAULT '',banner text);
CREATE TABLE IF NOT EXISTS guild_members(guild_id text REFERENCES guilds(id),user_id text REFERENCES users(id),role text NOT NULL DEFAULT 'member',PRIMARY KEY(guild_id,user_id));
COMMIT;
