BEGIN;
CREATE TABLE IF NOT EXISTS player_avatars(user_id text PRIMARY KEY REFERENCES users(id),display_name text NOT NULL,body_color text NOT NULL DEFAULT '#659db1',equipment jsonb NOT NULL DEFAULT '{}',current_room_id text NOT NULL DEFAULT 'town',last_x real NOT NULL DEFAULT 550,last_y real NOT NULL DEFAULT 590,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS connected_wallets(public_key text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),verified_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS wallet_challenges(id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),public_key text NOT NULL,message text NOT NULL,expires_at timestamptz NOT NULL,used boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS world_rooms(id text PRIMARY KEY,name text NOT NULL,data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS mochi_conversation_messages(id text PRIMARY KEY,mochi_id text NOT NULL REFERENCES mochis(id),user_id text NOT NULL REFERENCES users(id),role text NOT NULL CHECK(role IN('user','mochi')),text text NOT NULL,visibility text NOT NULL DEFAULT 'owner_only' CHECK(visibility IN('owner_only','room')),created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS conversations_pet ON mochi_conversation_messages(mochi_id,created_at DESC);
CREATE TABLE IF NOT EXISTS mochi_memories(id text PRIMARY KEY,mochi_id text NOT NULL REFERENCES mochis(id),type text NOT NULL,summary text NOT NULL,importance integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS token_payment_intents(id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),type text NOT NULL,mint text NOT NULL,decimals integer NOT NULL CHECK(decimals BETWEEN 0 AND 18),amount_raw numeric(40,0) NOT NULL CHECK(amount_raw>0),recipient text NOT NULL,sender text NOT NULL,status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','confirmed','failed','expired')),signature text UNIQUE,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS listing_reservations(listing_id text PRIMARY KEY REFERENCES player_shop_listings(id) ON DELETE CASCADE,intent_id text UNIQUE NOT NULL REFERENCES token_payment_intents(id),expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS mock_token_balances(user_id text PRIMARY KEY REFERENCES users(id),amount_raw numeric(40,0) NOT NULL CHECK(amount_raw>=0));
CREATE TABLE IF NOT EXISTS mock_token_ledger(id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),amount_raw numeric(40,0) NOT NULL,type text NOT NULL,intent_id text REFERENCES token_payment_intents(id),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS platform_revenue_records(id text PRIMARY KEY,intent_id text UNIQUE REFERENCES token_payment_intents(id),source text NOT NULL,token_mint text NOT NULL,amount_raw numeric(40,0) NOT NULL CHECK(amount_raw>=0),allocation_raw numeric(40,0),allocation_bps integer CHECK(allocation_bps BETWEEN 0 AND 10000),mock boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS cadence_buyback_records(id text PRIMARY KEY,revenue_id text REFERENCES platform_revenue_records(id),status text NOT NULL DEFAULT 'queued',allocated_raw numeric(40,0) NOT NULL,acquired_raw numeric(40,0),burned_raw numeric(40,0),dex_signature text UNIQUE,burn_signature text UNIQUE,verified_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),CHECK(status<>'verified' OR (dex_signature IS NOT NULL AND burn_signature IS NOT NULL AND verified_at IS NOT NULL)));
ALTER TABLE cadence_buyback_records ADD COLUMN IF NOT EXISTS spent_raw numeric(40,0);
COMMIT;

-- Additive human appearance; old body_color/equipment and all account records remain.
ALTER TABLE player_avatars ADD COLUMN IF NOT EXISTS appearance jsonb NOT NULL DEFAULT '{"style":"classic"}';
